version: "3.8"

services:
  app:
    build: .
    env_file: .env
    restart: unless-stopped
    depends_on: [redis]
    volumes:
      - ./src:/app/src:ro
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on: [app]
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/static:/usr/share/nginx/html:ro

  redis:
    image: redis:alpine
    restart: unless-stopped
